name: Upload Python Package

on:
  workflow_run: 
    workflows: [Django CI] 
    types: completed
  release: 
    types: [published]

permissions:
  contents: read

jobs:
  build:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      steps:
      - uses: actions/setup-python@v5.3.0
        with:
          python-version-file: poetry
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt install pipx
          pipx install poetry
          poetry install
          poetry build
          
  pypi-publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: upload release to PyPI
    runs-on: ubuntu-latest
    steps:
      # retrieve your distributions here
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
