name: Upload Python Package

on:
  workflow_run: 
    workflows: [Django CI] 
    types: completed
  release: 
    types: [published]

permissions:
  contents: read

jobs:
  pypi-publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: upload release to PyPI
    runs-on: ubuntu-latest
    steps:
      # retrieve your distributions here
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
