name: Release

on:
  release: 
    types: [published]

permissions:
  contents: read

jobs:
  publish-pypi:
      runs-on: ubuntu-latest
      permissions:
        id-token: write
      steps:
      - uses: actions/setup-python@v5.3.0
        with:
           python-version: "^3.12"
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt install pipx
          pipx install poetry
          poetry install
          poetry build
      - name: upload release to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

          
